version: '3.8'

services:
  node-server:
    build:
      context: ./
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      NODE_ENV: production
    restart: unless-stopped

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: simplepassword123456
      MYSQL_DATABASE: leitura_atualizada
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  prisma:
    image: prismagraphql/prisma:1.34.10
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: simplepassword123456
        port: 4466
        databases:
          default:
            connector: mysql
            host: db
            port: 3306
            user: root
            password: simplepassword123456
            connectionLimit: 10

volumes:
  mysql-data:
